### ISSUE TITLE
对markdown不怎么支持啊

### ISSUE THREAD

**Issue by saowu** [zoujiayu/Tale-Theme-NexT.Pisces#1]

**Comment by zoujiayu** [comment]
首先感谢你的提问.
1.Tale文章编辑器是支持markdown语法，Tale将markdown转换为html，通过${show_content()}函数输出到前端。前端是不用另外修改支持markdown的。
2.可能是你markdown语法有误。
![0](https://user-images.githubusercontent.com/20484791/44700271-db9df000-aaba-11e8-8a21-0d3fb067e346.PNG)
![1](https://user-images.githubusercontent.com/20484791/44700272-dc368680-aaba-11e8-8a5a-52d1c3279908.PNG)

**Comment by saowu** [comment]
是吗，编辑时预览自正确的，转换成html就没效果哦，我有空再试试吧，谢谢

**Comment by zoujiayu** [comment]
@laolatiao 
方便把不生效的markdown代码发出来吗。
Tale的markdown语法支持本身就有问题
